local json = require("dkjson")
local utf8 = require("utf8")
local hexterm = require("hexterm")
local utils = require("scripts.utils")

--- @param url string
local function fetch_json(url)
	local file = io.popen("curl -s " .. url)

	if file == nil then
		print("Error: Failed to load JSON from URL")
		os.exit(1)
	end

	local buf = file:read("*all")
	file:close()

	return json.decode(buf)
end

--- @param key string
--- @param meta table
local function build_icon(key, meta)
	local content = ""

	content = content .. string.format('\t["%s"] = {\n', key)
	content = content .. string.format('\t\ticon = "%s",\n', utf8.char(meta.codepoint))
	content = content .. string.format('\t\tcolor = "%s",\n', meta.color)
	content = content .. string.format('\t\tcterm_color = "%s",\n', hexterm(meta.color))
	content = content .. string.format('\t\tname = "%s",\n', utils.pascal_case(key))
	content = content .. "\t},\n"

	return content
end

local mapping_url = "https://mskelton.github.io/termicons/termicons.json"
local mappings = fetch_json(mapping_url)

local content = [[
--- This file is auto-generated by generate-icons.lua!

local M = {}

M.icons = {
]]

for key, meta in utils.sorted_pairs(mappings) do
	content = content .. build_icon(key, meta)
end

content = content .. [[
}

return M
]]

utils.write_file("lua/termicons/icons.lua", content)
