name: Build
on:
  push:
  repository_dispatch:
    types: [update-icons]
permissions:
  contents: write
  pull-requests: write
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9
      - name: Setup Luarocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Install dependencies
        run: luarocks make
      - name: Generate icons and mappings
        run: make generate
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: chore/update-icons
          commit-message: "chore: Auto-update icons"
          title: "Auto-update icons"
          body: |
            Update icons and file mappings from [termicons](https://github.com/mskelton/termicons).
